### ISSUE TITLE
how to add all champion data ?

### ISSUE THREAD

**Issue by nongnoobjung** [farzaa/DeepLeague#13]
how to add all champion data ?

**Comment by timogilvie** [comment]
See issue #10 The training data only included a subset of champions from pro play. So we need to train the model on some different examples, and/or re-train the model to know that there are lots of missing champs and lower confidence when it's unknown.

**Comment by farzaa** [comment]
Exactly. Right now, I have data for many champs that ended up getting cut out. 

I'm looking into retraining YOLO with the [focal loss](https://arxiv.org/abs/1708.02002) soon to account for the discrimination in the data.

**Comment by farzaa** [comment]
If you have any other questions, reopen this issue :D
