### ISSUE TITLE
Missing local file: vod_info.csv

### ISSUE THREAD

**Issue by timogilvie** [farzaa/DeepLeague#15]
There's a reference to a locally stored file vod_info.csv in download_youtube.py. I assume this is the list of VOD for the training data. Could we add to the repo so this works? 

# tuples of file_name, youtube_link, game_start_time, game_end_time
CSV_FILE_PATH = '/Users/flynn/Documents/DeepLeague/data/vod_info.csv'

**Comment by farzaa** [comment]
Oh, woopsies. 
 
Yeah, so most of those scripts are just to show off how I created my dataset so you could create your own. Thats why I don't give explicit instructions on how to run it.

But, you can find the file [here](https://docs.google.com/spreadsheets/d/10m0GiSeBnmfNBF8aujjdbWaWYfZYY5I0C-OwsjRifw8/edit?usp=sharing). But, you would still need the JSON files. I have those to, just open this issue up again if you actually need them!
