### ISSUE TITLE
Temporal metadata or ordering of images in dataset?

### ISSUE THREAD

**Issue by nlml** [farzaa/DeepLeague#16]
Hi there,

Thanks for your efforts with this model + dataset. I'm looking to use your dataset as part of training my own champions detection/tracking model and it should be a big help.

I would like to try and use temporal information to inform my model (i.e., feed the frames into an LSTM + Conv style model in sequential order), however it appears this information is absent from your dataset?

I downloaded the dataset from the torrent here: https://archive.org/details/DeepLeague100K

I see there is an sqlite file containing some metadata, but I can't make much sense of what the metadata is supposed to be.

Plus when I sequentially plot images from the dataset, it appears they are in a random order.

Do you possibly have timestamps for each of the frames in the dataset somewhere? Or is there some ordering I can apply so that the frames are sequential?

Cheers,
Liam

**Comment by farzaa** [comment]
Hi there! 

I'm not sure what that sqlite file is, mind throwing it over to me? I never dropped that in. And the dataset has actually been shuffled and saved as a .npz file so that the temporal quality of the frames isn't saved. 

I could perhaps try and create the dataset for you again and this time make sure I don't shuffle it. If you're still interested, just let me know :).

**Comment by nlml** [comment]
I think the sqlite file might be added by arxiv.org. It doesn't contain anything useful. Can't attach it right now but if you look at the torrent there you can see what I mean.

That would be useful, but I've scraped together my own dataset so it's probably fine :)  -- I guess you would need to run tesseract again to recreate the dataset?

**Comment by farzaa** [comment]
I actually have the entire dataset kept as jpg's for each game with a JSON file (for each game) identifying what timestamp each jpg represents.

And cool! Did you get the data from the websocket? If so, my function ```rescale_coordinates``` found [here](https://github.com/farzaa/DeepLeague/blob/master/Data%20Scripts/read_ocr_and_lolesport_data.py) will be useful :).

**Comment by nlml** [comment]
Yep I did get the data from the websocket. Though I found this approach to rescaling the coordinates seems more accurate:
```python
def _rescale_coordinates(game_data):
    # game_data is an [N, 2] shape array of coordinates from the websocket
    return (288 - 18) * game_data / 15000. + np.array([18, 18])
```
Would it perhaps be possible to reverse-engineer the timestamps for the randomly-ordered frames in the dataset you uploaded by using the same random seeds as you originally used to create the dataset?

**Comment by farzaa** [comment]
Hey!  I think what you mention at the end there is possible. I seed my RNG at 13, as you find [here](https://github.com/farzaa/DeepLeague/blob/master/Data%20Scripts/create_npz_file.py). Let me know what ends up happening, I'm super curious.

**Comment by farzaa** [comment]
I'm gonna close this, let me know if anything else comes up :).

**Comment by nlml** [comment]
No worries - I never got around to trying this but thanks for your help!
