### ISSUE TITLE
[help][Errno 2] No such file or directory: '/output/game_data.json'

### ISSUE THREAD

**Issue by li10141110** [farzaa/DeepLeague#17]
I implement your code as your readme in my macbook. It seems ok until the last command 'pythonw test_deep_league.py -out output youtube -yt https://www.youtube.com/watch?v=vPwZW1FvtWA -yt_path /output -start 0:00:30 -end 0:01:00 ' Could you help me and thank you in advance!

**Comment by ErikMelton** [comment]
Open your "test_deep_league.py" and search for the line with '/output/game_data.json'. Remove the first /, and then re-run the script, it should work just fine then.

**Comment by ErikMelton** [comment]
@farzaa this was closed by #19
