### ISSUE TITLE
yolo.cfg does not exist

### ISSUE THREAD

**Issue by Rummskartoffel** [farzaa/DeepLeague#20]
In the installation instructions, it says to download [yolo.cfg](https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolo.cfg), but this file does not exist, so the download request produces a 404 error. Is there an alternative?

**Comment by ErikMelton** [comment]
You should download the YOLOv2 config file from the pjreddie darknet repository. It works great with mine!

**Comment by farzaa** [comment]
I fixed the links.

Let me know if its all good now!

**Comment by macpriori** [comment]
I am seeing 404 error when using wget commands as indicated in the Quick Start description

link:
https://github.com/allanzelener/YAD2K

**Comment by farzaa** [comment]
Hey dude! Yeah, YAD2K Repo is a little messed up. I'll make a PR to fix that later. In the meantime,  the links here work fine! https://github.com/farzaa/DeepLeague
