### ISSUE TITLE
mac got valueError 

### ISSUE THREAD

**Issue by CXY037** [farzaa/DeepLeague#21]
when I try the commond pythonw test_deep_league.py -out output youtube -yt https://www.youtube.com/watch?v=vPwZW1FvtWA -yt_path /output -start 0:00:30 -end 0:01:00

Traceback (most recent call last):
  File "test_deep_league.py", line 164, in <module>
    yolo_model, _ = create_model(anchors, class_names)
  File "/Users/xiaoyu/deeplearn/deeplol/YAD2K/retrain_yolo.py", line 351, in create_model
    topless_yolo.load_weights(topless_yolo_path)
  File "/Users/xiaoyu/miniconda3/envs/DeepLeague/lib/python3.6/site-packages/keras/engine/topology.py", line 2667, in load_weights
    f, self.layers, reshape=reshape)
  File "/Users/xiaoyu/miniconda3/envs/DeepLeague/lib/python3.6/site-packages/keras/engine/topology.py", line 3365, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 129 layers into a model with 44 layers.

**Comment by farzaa** [comment]
Hey mate. Everything is working fine for me here. Are you using Conda?

**Comment by CXY037** [comment]
Yes I am using Conda

Farzain Majeed <notifications@github.com>于2018年5月10日 周四09:24写道：

**Comment by CXY037** [comment]
System is Mac OS 10.12
Xiaoyu Chen <xiaoyulaile@gmail.com>于2018年5月10日 周四12:04写道：

**Comment by farzaa** [comment]
Okay, so I haven't tested everything in a while. I just completed deleted my local repo and follow the instructions from scratch and its working fine.  I'm on 10.13 High Sierra but that shouldn't really matter. I also tested on an Ubuntu machine and everything seems okay.

I'd say try once more to do everything from scratch and if stuff is still messed up than let me know and we can dig deeper.

**Comment by CXY037** [comment]
Ok thx a lot
Farzain Majeed <notifications@github.com>于2018年5月13日 周日03:15写道：

**Comment by ErikMelton** [comment]
` ValueError: You are trying to load a weight file containing 129 layers into a model with 44 layers.`

Looks like you have the incorrect YOLO configuration file. Download the correct one, (YOLOv2 works for me), and try again.

**Comment by CXY037** [comment]
Ok thx
I will try
Erik Melton <notifications@github.com>于2018年5月18日 周五17:33写道：

**Comment by farzaa** [comment]
If your still having this issue let me know.

Going to close the issue for now.
