### ISSUE TITLE
Your JSON sample

### ISSUE THREAD

**Issue by Steve1820** [farzaa/DeepLeague#22]
Hey! Great repo :-)

I was just wondering how did you generate the JSON you linked here: https://jsonbin.io/5a5fa15013a3b731a42f50af

Love this.

Steve

**Comment by farzaa** [comment]
Hey Steve.

So, this JSON was not generated :). You can read more here - https://medium.com/@farzatv/deepleague-part-2-the-technical-details-374439e7e09a

Feel free to email me if you more questions like this! FarzaDoesStuff@gmail.com
