### ISSUE TITLE
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'leaky_relu'

### ISSUE THREAD

**Issue by Steve1820** [farzaa/DeepLeague#23]
Hey guys,

Any ideas? Getting this error:

AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'leaky_relu'

Steve

**Comment by Steve1820** [comment]
![image](https://user-images.githubusercontent.com/20320870/41499132-b7c6bb38-71be-11e8-8f25-2f8809773366.png)

**Comment by farzaa** [comment]
Hmmm, what command are you running when this happens?
Also, whats the exact version of Keras and Tensorflow you are using?

**Comment by Steve1820** [comment]
Command I am using when this happens:

pythonw yad2k.py yolo.cfg yolo.weights model_data/yolo.h5

Tensorflow Version:
![image](https://user-images.githubusercontent.com/20320870/41503508-b945a216-7219-11e8-800c-6b8b4aaa8a79.png)

Keras Version:
![image](https://user-images.githubusercontent.com/20320870/41503513-cb630268-7219-11e8-8c8c-90674a17e1cc.png)

**Comment by farzaa** [comment]
Yo! 

So, I just did the whole installation process from scratch and everything worked fine for me. I downloaded the latest version of everything, pulled the repo into a fresh folder, and followed the installation instructions. 

I'd say to create a new virtual environment and do the steps again just to make sure you didn't miss anything. Let me know what happens!

**Comment by Steve1820** [comment]
You're a legend.

Works now.

**Comment by farzaa** [comment]
<3
