### ISSUE TITLE
The download link for data set is not working

### ISSUE THREAD

**Issue by wenzheli** [farzaa/DeepLeague#24]
It throws access denied exception...

**Comment by squishytofu042** [comment]
Me too. This is the error I get:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
      <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>E47F7B9E889A484B</RequestId><HostId>0qHumhJQ64/Rnt0f2W2OoY7Mw/wtz0adzh+J3/zA+0psZ2L0wxqB0c1jB3PTuLvMcHh1cAwvbKo=</HostId></Error>

Can you please help!

**Comment by farzaa** [comment]
Oh shit my bad.

**Comment by farzaa** [comment]
Fixed :).
