### ISSUE TITLE
Windows Installation Instructions

### ISSUE THREAD

**Issue by farzaa** [farzaa/DeepLeague#5]
I know people have gotten this working by using an Ubuntu [subsystem](https://docs.microsoft.com/en-us/windows/wsl/install-win10) which comes with Windows 10, but it may be useful to get it working on normal old Windows. 

Perhaps someone can create some instructions as others have done with the Ubuntu instructions. In the perfect world, there could just me a windows_enviroment.yml file (like the existing requirements.yml file for Ubuntu) and people can just do

`conda env create -f windows_enviroment.yml`

**Comment by farzaa** [comment]
This is still needed if anyone wants to attack it!

**Comment by NiklasWilke** [comment]
No clue how to do it but will try to make it work somehow :D!
Learning on the job i guess

**Comment by ErikMelton** [comment]
I've gotten it to work, it's pretty easy to setup. I'll make a PR when I get some spare time :)

**Comment by NiklasWilke** [comment]
oh great! 

Much appreciated :))

**Comment by cschar** [comment]
@ErikMelton is that commit hanging around somewhere on github? =)
