### ISSUE TITLE
I am making this issue to tell people to make issues :)!

### ISSUE THREAD

**Issue by farzaa** [farzaa/DeepLeague#6]
DeepLeague is open source and I'm happy people are already contributing.

If you have any ideas for DeepLeague, just create an issue and give it the "enhancement" label, doesn't matter how crazy it is! I want people to contribute new ideas and then me and others can work on them.  The first step is always the idea and then people will get inspired to attack the problems.

And of course, if you find bugs or have issues then definitely create an issue.

**Comment by jinchuika** [comment]
We could also make a Project Wiki with tutorials, use cases and project goals? Who knows, it could be helpful ;)

**Comment by farzaa** [comment]
Would you like to start that? Once you do I'd be happy to contribute a bunch to it :)

**Comment by jinchuika** [comment]
It looks like I can't create the Wiki. I probably need permissions to do that.

**Comment by farzaa** [comment]
Done!
