### ISSUE TITLE
Output coordinates as a CSV.

### ISSUE THREAD

**Issue by farzaa** [farzaa/DeepLeague#7]
DeepLeague currently just draws bounding boxes on an image and sends these to the "output/" folder.

I've had analysts contact me who have said it'd be much easier to have this data exported as a CSV file. In the `test_deep_league.py` file you'll see this

`     out_boxes, out_scores, out_classes = sess.run( [boxes, scores, classes], feed_dict={.....`
     

This is simply feeding an image to the neural network, which you don't really need to worry about. But you do need its output!

`out_boxes` is the actual bounding box (top, left, bottom, right), `out_scores` is the confidence score, and `out_classes` is the champion label which will be a number.  `model_data/league_classes.txt` will tell you what champion this number corresponds to.

**Comment by jinchuika** [comment]
Perhaps you could post an example of how that CSV would look? As a starting point, it could be easier to structure it as a JSON file just tu have an idea. What do you think of something like:

```
[
    {
        "timestamp": 0001,
        "champions": [
            {
                "name": "orianna",
                "score": 0.98,
                "top": 150,
                "bottom": 250,
                "left": 300,
                "right": 400
            },
            {
                "name": "ahri",
                "score": 0.87,
                "top": 350,
                "bottom": 450,
                "left": 200,
                "right": 300
            }
        ]
    }
]
```

And the CSV version could be like:

| timestamp | champion | score  | top | bottom | left | right
| ------------- |:-------------:| -----:| -----:| -----:| -----:| -----:|
| 0001      | orianna | 0.98 | 150 | 250 | 300 | 400
| 0001      | ahri | 0.87 | 350 | 450 | 200 | 300

**Comment by farzaa** [comment]
Ah, yes! That'd be smart. 

Your CSV is near perfect. I'd just add one more field called "center" which would calculate the center of the bounding box and just get rid of the top, bottom, left, right fields. We can easily calculate those fields using "center". Plus, I think most analysts won't really understand the concept of a bounding box and understanding the champ on the map as one point may make more sense.

Thoughts?

**Comment by timogilvie** [comment]
I wrote code to handle this using the logging framework. Takes a logfile command line argument and sends to that file. Otherwise output goes to stdout. Add me and I'll submit a PR.

**Comment by farzaa** [comment]
Dope! And not sure what you mean by add you.

I think anyone can submit a PR.

**Comment by timogilvie** [comment]
Yup. User error. Just submitted a PR
